name: Clipping Diario Telecom

on:
  # schedule:
  # - cron: '0 12 * * 1-5'
  workflow_dispatch:

jobs:
  clipping:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: |
          pip install google-genai beautifulsoup4 requests

      - name: Executar script de clipping
        env:
          # Adicione todas as variáveis que o script Python vai ler
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: python gera_clipping.py
